# Generated by Django 4.0.4 on 2022-05-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('registration', models.PositiveIntegerField(null=True)),
                ('kilometers', models.PositiveIntegerField(null=True)),
                ('mileage', models.PositiveIntegerField(null=True)),
                ('location', models.CharField(max_length=150)),
            ],
        ),
    ]
