# Generated by Django 4.0.4 on 2022-06-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bikes',
            name='last_date',
        ),
        migrations.AddField(
            model_name='bikes',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
