# Generated by Django 4.0.4 on 2022-05-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bikes',
            old_name='location',
            new_name='fuel',
        ),
        migrations.AddField(
            model_name='bikes',
            name='owners',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bikes',
            name='registration',
            field=models.IntegerField(null=True),
        ),
    ]
