# Generated by Django 4.0.4 on 2022-06-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_remove_bikes_last_date_bikes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
