# Generated by Django 4.0.4 on 2022-06-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_bikes_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bikes',
            name='amount',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
